################################################
# SETUP
################################################

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

# Build settings
markdown: kramdown
highlighter: rouge

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
    provider: false
    statcounter:
        sc_project  :
        sc_security :
        sc_invisible: 1
        sc_text     : 2
    google:
        tracking_id: ''

plugins:
  - jekyll-seo-tag

#################################################
# CUSTOMIZATION
#################################################

title: Johan Hektor
description: Johan Hektor | Application Expert in Image Analysis | Lund University

url: ""
baseurl: ""

# start year for copyright
start_year: "2020"

colors:
  background: "#FFFFFF;" #"#F4D6CC;" #"#FFFFFF;"
  separator: "#F4B860;" #"#042352;"

author:
    name: "Johan Hektor"

# manage your co-authors from here

coauthors:
  stefanos:
      name: Stefanos Athanasopoulos
      web: https://portal.research.lu.se/portal/en/persons/stefanos-athanasopoulos(a2b2efe0-7c5d-413f-872e-03c763ad2de7).html
  tbacker:
      name: Thomas Bäcker
  ocastelnau:
      name: Olivier Castelnau
      web: https://pimm.artsetmetiers.fr/user/54
  yacoutinho:
      name: Yuri Amorim Coutinho
      #web: https://www.robertbrianurl.org
  alc:
      name: ALC Conceiçao
  jonas:
      name: Jonas Engqvist
      web: https://portal.research.lu.se/portal/en/persons/jonas-engqvist(a71a76e1-011f-4e0e-a351-4c889c51b0f5).html
  fgrennerat:
      name: Fanny Grennerat
  sven:
      name: Sven Gutschmidt
  jbmarijon:
      name: Jean-Baptiste Marijon
  steve:
      name: Stephen Hall
      web: http://www.solid.lth.se/staff/hall-stephen/
  shaas:
      name: Silvio Haas
  hakan:
      name: Håkan Hallberg
  zoltan:
      name: Zoltan Hegedüs
  axel:
      name: Axel Henningsson
  srini:
      name: Srinivasan Iyengar
  jkelleher:
      name: Joe Kelleher
  anil:
      name: Anil Kunwar
      #web: https://www.aliceadamurl.org
  emanuel:
      name: Emanuel Larsson
  flenrick:
      name: Filip Lenrick
  ulrich:
      name: Ulrich Lienert
  snomoto:
      name: Sukeharu Nomoto
  hma:
      name: Haitao Ma
  jsmicha:
      name: Jean-Sebastién Micha
  timo:
      name: Timo Müller
  nele:
      name: Nele Moelans
      web: http://nele.studentenweb.org
  tpirling:
      name: Thilo Pirling
  orobach:
      name: Odile Robach
  matti:
      name: Matti Ristinmaa
  jon:
      name: Jon Wright
